version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskpilot_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ahsen
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskpilot_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
